# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileportal', '0002_auto_20170609_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsite',
            name='CurrentSem',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentsite',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
